"""add parent_id to tag

Revision ID: 63a8f05b7c83
Revises: ae290dce401b
Create Date: 2026-06-29 23:14:41.558311

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '63a8f05b7c83'
down_revision = 'ae290dce401b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insight_entry',
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('ai_interpretation', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('linked_digest_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insight_entry_parent_id'), 'insight_entry', ['parent_id'], unique=False)
    op.drop_constraint(op.f('item_owner_id_fkey'), 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_pushmessage_status'), table_name='pushmessage')
    op.drop_index(op.f('ix_pushmessage_user_id'), table_name='pushmessage')
    op.drop_constraint(op.f('pushmessage_content_record_id_fkey'), 'pushmessage', type_='foreignkey')
    op.drop_constraint(op.f('pushmessage_subscription_id_fkey'), 'pushmessage', type_='foreignkey')
    op.drop_index(op.f('ix_scheduledtask_biz_type'), table_name='scheduledtask')
    op.drop_index(op.f('ix_scheduledtask_enabled'), table_name='scheduledtask')
    op.add_column('tag', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.create_index(op.f('ix_tag_parent_id'), 'tag', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'tag', 'tag', ['parent_id'], ['id'])
    op.drop_index(op.f('ix_tagsynonym_synonym'), table_name='tagsynonym')
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_constraint(op.f('user_username_key'), 'user', type_='unique')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_index(op.f('ix_userdevice_user_id'), table_name='userdevice')
    op.drop_constraint(op.f('uq_userdevice_user_platform_device'), 'userdevice', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_userdevice_user_platform_device'), 'userdevice', ['user_id', 'platform', 'device_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_userdevice_user_id'), 'userdevice', ['user_id'], unique=False)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_unique_constraint(op.f('user_username_key'), 'user', ['username'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_tagsynonym_synonym'), 'tagsynonym', ['synonym'], unique=True)
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_index(op.f('ix_tag_parent_id'), table_name='tag')
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    op.drop_column('tag', 'parent_id')
    op.create_index(op.f('ix_scheduledtask_enabled'), 'scheduledtask', ['enabled'], unique=False)
    op.create_index(op.f('ix_scheduledtask_biz_type'), 'scheduledtask', ['biz_type'], unique=False)
    op.create_foreign_key(op.f('pushmessage_subscription_id_fkey'), 'pushmessage', 'subscription', ['subscription_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('pushmessage_content_record_id_fkey'), 'pushmessage', 'contentrecord', ['content_record_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_pushmessage_user_id'), 'pushmessage', ['user_id'], unique=False)
    op.create_index(op.f('ix_pushmessage_status'), 'pushmessage', ['status'], unique=False)
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key(op.f('item_owner_id_fkey'), 'item', 'user', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_insight_entry_parent_id'), table_name='insight_entry')
    op.drop_table('insight_entry')
    # ### end Alembic commands ###
