// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8009' | (string & {});
};

/**
 * AddDataSourceConfigM
 */
export type AddDataSourceConfigM = {
    /**
     * Name
     */
    name: string;
    /**
     * Source Type
     */
    source_type: string;
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Config
     */
    config?: {
        [key: string]: unknown;
    };
};

/**
 * AddLLMConfigM
 */
export type AddLlmConfigM = {
    /**
     * Name
     */
    name: string;
    /**
     * Provider
     */
    provider?: string;
    /**
     * Api Key
     */
    api_key: string;
    /**
     * Base Url
     */
    base_url?: string;
    /**
     * Model
     */
    model?: string;
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Is Default
     */
    is_default?: boolean;
    /**
     * Extra
     */
    extra?: {
        [key: string]: unknown;
    };
};

/**
 * AddScheduledTaskM
 */
export type AddScheduledTaskM = {
    /**
     * Name
     */
    name: string;
    /**
     * Biz Type
     */
    biz_type: string;
    /**
     * Biz Id
     */
    biz_id?: number | null;
    /**
     * Cron Expr
     */
    cron_expr: string;
    /**
     * Enabled
     */
    enabled?: boolean;
};

/**
 * AddSubscriptionM
 */
export type AddSubscriptionM = {
    /**
     * Name
     */
    name: string;
    /**
     * Keywords
     */
    keywords?: Array<string>;
    /**
     * Sources
     */
    sources?: Array<string>;
    /**
     * Schedule Type
     */
    schedule_type?: string;
    /**
     * Schedule Cron
     */
    schedule_cron?: string;
    /**
     * Enabled
     */
    enabled?: boolean;
};

/**
 * AddSynonymM
 */
export type AddSynonymM = {
    /**
     * Tag Id
     */
    tag_id: number;
    /**
     * Synonym
     */
    synonym: string;
};

/**
 * Body_login-login_access_token
 */
export type BodyLoginLoginAccessToken = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * DeleteScheduledTaskM
 */
export type DeleteScheduledTaskM = {
    /**
     * Id
     */
    id: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HealthStatus
 */
export type HealthStatus = {
    /**
     * Status
     */
    status: string;
    /**
     * Pg
     */
    pg: boolean;
    /**
     * Mongo
     */
    mongo: boolean;
    /**
     * Redis
     */
    redis: boolean;
    /**
     * Version
     */
    version: string;
};

/**
 * ItemCreate
 */
export type ItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemPublic
 */
export type ItemPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Owner Id
     */
    owner_id: number;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ItemUpdate
 */
export type ItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ItemsPublic
 */
export type ItemsPublic = {
    /**
     * Data
     */
    data: Array<ItemPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ListMessagesM
 */
export type ListMessagesM = {
    /**
     * Push Date
     */
    push_date?: string | null;
    /**
     * Importance
     */
    importance?: string | null;
    /**
     * Is Read
     */
    is_read?: boolean | null;
    /**
     * Page Num
     */
    page_num?: number;
    /**
     * Page Size
     */
    page_size?: number;
};

/**
 * ListScheduledTaskM
 */
export type ListScheduledTaskM = {
    /**
     * Biz Type
     */
    biz_type?: string | null;
    /**
     * Enabled
     */
    enabled?: boolean | null;
    /**
     * Page Num
     */
    page_num?: number;
    /**
     * Page Size
     */
    page_size?: number;
};

/**
 * ListTagM
 */
export type ListTagM = {
    /**
     * Keyword
     */
    keyword?: string | null;
    /**
     * Category
     */
    category?: string | null;
    /**
     * Page Num
     */
    page_num?: number;
    /**
     * Page Size
     */
    page_size?: number;
};

/**
 * MarkAsReadM
 */
export type MarkAsReadM = {
    /**
     * Id List
     */
    id_list: Array<number>;
};

/**
 * MergeTagM
 */
export type MergeTagM = {
    /**
     * Source Tag Ids
     */
    source_tag_ids: Array<number>;
    /**
     * Target Tag Id
     */
    target_tag_id: number;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PreviewCronM
 */
export type PreviewCronM = {
    /**
     * Cron Expr
     */
    cron_expr: string;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * RemoveSynonymM
 */
export type RemoveSynonymM = {
    /**
     * Synonym Id
     */
    synonym_id: number;
};

/**
 * RenameTagM
 */
export type RenameTagM = {
    /**
     * Tag Id
     */
    tag_id: number;
    /**
     * New Name
     */
    new_name: string;
};

/**
 * ResendM
 */
export type ResendM = {
    /**
     * Id
     */
    id: number;
};

/**
 * RetryTagM
 */
export type RetryTagM = {
    /**
     * Id
     */
    id: number;
};

/**
 * RunNowM
 */
export type RunNowM = {
    /**
     * Id
     */
    id: number;
};

/**
 * SearchContentsM
 */
export type SearchContentsM = {
    /**
     * Subscription Id
     */
    subscription_id?: number | null;
    /**
     * Category
     */
    category?: string | null;
    /**
     * Importance
     */
    importance?: string | null;
    /**
     * Llm Status
     */
    llm_status?: string | null;
    /**
     * Keyword
     */
    keyword?: string | null;
    /**
     * Page Num
     */
    page_num?: number;
    /**
     * Page Size
     */
    page_size?: number;
};

/**
 * SetDefaultLLMConfigM
 */
export type SetDefaultLlmConfigM = {
    /**
     * Id
     */
    id: number;
};

/**
 * TestLLMConfigM
 */
export type TestLlmConfigM = {
    /**
     * Id
     */
    id?: number | null;
    /**
     * Api Key
     */
    api_key?: string | null;
    /**
     * Base Url
     */
    base_url?: string | null;
    /**
     * Model
     */
    model?: string | null;
    /**
     * Provider
     */
    provider?: string | null;
};

/**
 * ToggleDataSourceConfigM
 */
export type ToggleDataSourceConfigM = {
    /**
     * Id
     */
    id: number;
    /**
     * Enabled
     */
    enabled: boolean;
};

/**
 * ToggleScheduledTaskM
 */
export type ToggleScheduledTaskM = {
    /**
     * Id
     */
    id: number;
    /**
     * Enabled
     */
    enabled: boolean;
};

/**
 * ToggleSubscriptionM
 */
export type ToggleSubscriptionM = {
    /**
     * Id
     */
    id: number;
    /**
     * Enabled
     */
    enabled: boolean;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdateDataSourceConfigM
 */
export type UpdateDataSourceConfigM = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Source Type
     */
    source_type?: string | null;
    /**
     * Enabled
     */
    enabled?: boolean | null;
    /**
     * Config
     */
    config?: {
        [key: string]: unknown;
    } | null;
};

/**
 * UpdateLLMConfigM
 */
export type UpdateLlmConfigM = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Provider
     */
    provider?: string | null;
    /**
     * Api Key
     */
    api_key?: string | null;
    /**
     * Base Url
     */
    base_url?: string | null;
    /**
     * Model
     */
    model?: string | null;
    /**
     * Enabled
     */
    enabled?: boolean | null;
    /**
     * Is Default
     */
    is_default?: boolean | null;
    /**
     * Extra
     */
    extra?: {
        [key: string]: unknown;
    } | null;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UpdatePreferenceM
 */
export type UpdatePreferenceM = {
    /**
     * Channels
     */
    channels?: {
        [key: string]: boolean;
    } | null;
    /**
     * Push Time
     */
    push_time?: string | null;
    /**
     * Timezone
     */
    timezone?: string | null;
    /**
     * Daily Digest
     */
    daily_digest?: boolean | null;
    /**
     * Importance Filter
     */
    importance_filter?: Array<string> | null;
};

/**
 * UpdateScheduledTaskM
 */
export type UpdateScheduledTaskM = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Cron Expr
     */
    cron_expr?: string | null;
    /**
     * Enabled
     */
    enabled?: boolean | null;
};

/**
 * UpdateSubscriptionM
 */
export type UpdateSubscriptionM = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Keywords
     */
    keywords?: Array<string> | null;
    /**
     * Sources
     */
    sources?: Array<string> | null;
    /**
     * Schedule Type
     */
    schedule_type?: string | null;
    /**
     * Schedule Cron
     */
    schedule_cron?: string | null;
    /**
     * Enabled
     */
    enabled?: boolean | null;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: number;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Username
     */
    username?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Username
     */
    username?: string | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type LoginLoginAccessTokenData = {
    body: BodyLoginLoginAccessToken;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginLoginAccessTokenError = LoginLoginAccessTokenErrors[keyof LoginLoginAccessTokenErrors];

export type LoginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginLoginAccessTokenResponse = LoginLoginAccessTokenResponses[keyof LoginLoginAccessTokenResponses];

export type LoginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type LoginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type LoginTestTokenResponse = LoginTestTokenResponses[keyof LoginTestTokenResponses];

export type LoginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type LoginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordError = LoginRecoverPasswordErrors[keyof LoginRecoverPasswordErrors];

export type LoginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginRecoverPasswordResponse = LoginRecoverPasswordResponses[keyof LoginRecoverPasswordResponses];

export type LoginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type LoginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginResetPasswordError = LoginResetPasswordErrors[keyof LoginResetPasswordErrors];

export type LoginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginResetPasswordResponse = LoginResetPasswordResponses[keyof LoginResetPasswordResponses];

export type LoginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type LoginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordHtmlContentError = LoginRecoverPasswordHtmlContentErrors[keyof LoginRecoverPasswordHtmlContentErrors];

export type LoginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type LoginRecoverPasswordHtmlContentResponse = LoginRecoverPasswordHtmlContentResponses[keyof LoginRecoverPasswordHtmlContentResponses];

export type UsersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type UsersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUsersError = UsersReadUsersErrors[keyof UsersReadUsersErrors];

export type UsersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type UsersReadUsersResponse = UsersReadUsersResponses[keyof UsersReadUsersResponses];

export type UsersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type UsersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersCreateUserError = UsersCreateUserErrors[keyof UsersCreateUserErrors];

export type UsersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersCreateUserResponse = UsersCreateUserResponses[keyof UsersCreateUserResponses];

export type UsersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserMeResponse = UsersDeleteUserMeResponses[keyof UsersDeleteUserMeResponses];

export type UsersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserMeResponse = UsersReadUserMeResponses[keyof UsersReadUserMeResponses];

export type UsersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserMeError = UsersUpdateUserMeErrors[keyof UsersUpdateUserMeErrors];

export type UsersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserMeResponse = UsersUpdateUserMeResponses[keyof UsersUpdateUserMeResponses];

export type UsersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type UsersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdatePasswordMeError = UsersUpdatePasswordMeErrors[keyof UsersUpdatePasswordMeErrors];

export type UsersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersUpdatePasswordMeResponse = UsersUpdatePasswordMeResponses[keyof UsersUpdatePasswordMeResponses];

export type UsersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type UsersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersRegisterUserError = UsersRegisterUserErrors[keyof UsersRegisterUserErrors];

export type UsersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersRegisterUserResponse = UsersRegisterUserResponses[keyof UsersRegisterUserResponses];

export type UsersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUserByIdError = UsersReadUserByIdErrors[keyof UsersReadUserByIdErrors];

export type UsersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserByIdResponse = UsersReadUserByIdResponses[keyof UsersReadUserByIdResponses];

export type UsersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserError = UsersUpdateUserErrors[keyof UsersUpdateUserErrors];

export type UsersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserResponse = UsersUpdateUserResponses[keyof UsersUpdateUserResponses];

export type UtilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type UtilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UtilsTestEmailError = UtilsTestEmailErrors[keyof UtilsTestEmailErrors];

export type UtilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type UtilsTestEmailResponse = UtilsTestEmailResponses[keyof UtilsTestEmailResponses];

export type UtilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type UtilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type UtilsHealthCheckResponse = UtilsHealthCheckResponses[keyof UtilsHealthCheckResponses];

export type ItemsReadItemsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/items/';
};

export type ItemsReadItemsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsReadItemsError = ItemsReadItemsErrors[keyof ItemsReadItemsErrors];

export type ItemsReadItemsResponses = {
    /**
     * Successful Response
     */
    200: ItemsPublic;
};

export type ItemsReadItemsResponse = ItemsReadItemsResponses[keyof ItemsReadItemsResponses];

export type ItemsCreateItemData = {
    body: ItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/items/';
};

export type ItemsCreateItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsCreateItemError = ItemsCreateItemErrors[keyof ItemsCreateItemErrors];

export type ItemsCreateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsCreateItemResponse = ItemsCreateItemResponses[keyof ItemsCreateItemResponses];

export type ItemsDeleteItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type ItemsDeleteItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsDeleteItemError = ItemsDeleteItemErrors[keyof ItemsDeleteItemErrors];

export type ItemsDeleteItemResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ItemsDeleteItemResponse = ItemsDeleteItemResponses[keyof ItemsDeleteItemResponses];

export type ItemsReadItemData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type ItemsReadItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsReadItemError = ItemsReadItemErrors[keyof ItemsReadItemErrors];

export type ItemsReadItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsReadItemResponse = ItemsReadItemResponses[keyof ItemsReadItemResponses];

export type ItemsUpdateItemData = {
    body: ItemUpdate;
    path: {
        /**
         * Id
         */
        id: number;
    };
    query?: never;
    url: '/api/v1/items/{id}';
};

export type ItemsUpdateItemErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ItemsUpdateItemError = ItemsUpdateItemErrors[keyof ItemsUpdateItemErrors];

export type ItemsUpdateItemResponses = {
    /**
     * Successful Response
     */
    200: ItemPublic;
};

export type ItemsUpdateItemResponse = ItemsUpdateItemResponses[keyof ItemsUpdateItemResponses];

export type HealthHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type HealthHealthCheckResponses = {
    /**
     * Successful Response
     */
    200: HealthStatus;
};

export type HealthHealthCheckResponse = HealthHealthCheckResponses[keyof HealthHealthCheckResponses];

export type LlmConfigAddLlmConfigData = {
    body: AddLlmConfigM;
    path?: never;
    query?: never;
    url: '/api/v1/LLMConfig/add';
};

export type LlmConfigAddLlmConfigErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LlmConfigAddLlmConfigError = LlmConfigAddLlmConfigErrors[keyof LlmConfigAddLlmConfigErrors];

export type LlmConfigAddLlmConfigResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LlmConfigListLlmConfigsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/LLMConfig/list';
};

export type LlmConfigListLlmConfigsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LlmConfigUpdateLlmConfigData = {
    body: UpdateLlmConfigM;
    path?: never;
    query?: never;
    url: '/api/v1/LLMConfig/update';
};

export type LlmConfigUpdateLlmConfigErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LlmConfigUpdateLlmConfigError = LlmConfigUpdateLlmConfigErrors[keyof LlmConfigUpdateLlmConfigErrors];

export type LlmConfigUpdateLlmConfigResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LlmConfigDeleteLlmConfigData = {
    body: SetDefaultLlmConfigM;
    path?: never;
    query?: never;
    url: '/api/v1/LLMConfig/delete';
};

export type LlmConfigDeleteLlmConfigErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LlmConfigDeleteLlmConfigError = LlmConfigDeleteLlmConfigErrors[keyof LlmConfigDeleteLlmConfigErrors];

export type LlmConfigDeleteLlmConfigResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LlmConfigSetDefaultLlmConfigData = {
    body: SetDefaultLlmConfigM;
    path?: never;
    query?: never;
    url: '/api/v1/LLMConfig/setDefault';
};

export type LlmConfigSetDefaultLlmConfigErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LlmConfigSetDefaultLlmConfigError = LlmConfigSetDefaultLlmConfigErrors[keyof LlmConfigSetDefaultLlmConfigErrors];

export type LlmConfigSetDefaultLlmConfigResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LlmConfigTestLlmConfigData = {
    body: TestLlmConfigM;
    path?: never;
    query?: never;
    url: '/api/v1/LLMConfig/test';
};

export type LlmConfigTestLlmConfigErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LlmConfigTestLlmConfigError = LlmConfigTestLlmConfigErrors[keyof LlmConfigTestLlmConfigErrors];

export type LlmConfigTestLlmConfigResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LlmConfigListProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/LLMConfig/listProviders';
};

export type LlmConfigListProvidersResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SubscriptionAddSubscriptionData = {
    body: AddSubscriptionM;
    path?: never;
    query?: never;
    url: '/api/v1/Subscription/add';
};

export type SubscriptionAddSubscriptionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubscriptionAddSubscriptionError = SubscriptionAddSubscriptionErrors[keyof SubscriptionAddSubscriptionErrors];

export type SubscriptionAddSubscriptionResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SubscriptionListSubscriptionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/Subscription/list';
};

export type SubscriptionListSubscriptionsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SubscriptionUpdateSubscriptionData = {
    body: UpdateSubscriptionM;
    path?: never;
    query?: never;
    url: '/api/v1/Subscription/update';
};

export type SubscriptionUpdateSubscriptionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubscriptionUpdateSubscriptionError = SubscriptionUpdateSubscriptionErrors[keyof SubscriptionUpdateSubscriptionErrors];

export type SubscriptionUpdateSubscriptionResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SubscriptionDeleteSubscriptionData = {
    body: RunNowM;
    path?: never;
    query?: never;
    url: '/api/v1/Subscription/delete';
};

export type SubscriptionDeleteSubscriptionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubscriptionDeleteSubscriptionError = SubscriptionDeleteSubscriptionErrors[keyof SubscriptionDeleteSubscriptionErrors];

export type SubscriptionDeleteSubscriptionResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SubscriptionToggleSubscriptionData = {
    body: ToggleSubscriptionM;
    path?: never;
    query?: never;
    url: '/api/v1/Subscription/toggle';
};

export type SubscriptionToggleSubscriptionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubscriptionToggleSubscriptionError = SubscriptionToggleSubscriptionErrors[keyof SubscriptionToggleSubscriptionErrors];

export type SubscriptionToggleSubscriptionResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SubscriptionListContentsData = {
    body: SearchContentsM;
    path?: never;
    query?: never;
    url: '/api/v1/Subscription/contents';
};

export type SubscriptionListContentsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubscriptionListContentsError = SubscriptionListContentsErrors[keyof SubscriptionListContentsErrors];

export type SubscriptionListContentsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SubscriptionRunNowData = {
    body: RunNowM;
    path?: never;
    query?: never;
    url: '/api/v1/Subscription/runNow';
};

export type SubscriptionRunNowErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubscriptionRunNowError = SubscriptionRunNowErrors[keyof SubscriptionRunNowErrors];

export type SubscriptionRunNowResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type SubscriptionRetryTagData = {
    body: RetryTagM;
    path?: never;
    query?: never;
    url: '/api/v1/Subscription/retryTag';
};

export type SubscriptionRetryTagErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SubscriptionRetryTagError = SubscriptionRetryTagErrors[keyof SubscriptionRetryTagErrors];

export type SubscriptionRetryTagResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DataSourceConfigAddDataSourceConfigData = {
    body: AddDataSourceConfigM;
    path?: never;
    query?: never;
    url: '/api/v1/DataSourceConfig/add';
};

export type DataSourceConfigAddDataSourceConfigErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DataSourceConfigAddDataSourceConfigError = DataSourceConfigAddDataSourceConfigErrors[keyof DataSourceConfigAddDataSourceConfigErrors];

export type DataSourceConfigAddDataSourceConfigResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DataSourceConfigListDataSourceConfigsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/DataSourceConfig/list';
};

export type DataSourceConfigListDataSourceConfigsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DataSourceConfigUpdateDataSourceConfigData = {
    body: UpdateDataSourceConfigM;
    path?: never;
    query?: never;
    url: '/api/v1/DataSourceConfig/update';
};

export type DataSourceConfigUpdateDataSourceConfigErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DataSourceConfigUpdateDataSourceConfigError = DataSourceConfigUpdateDataSourceConfigErrors[keyof DataSourceConfigUpdateDataSourceConfigErrors];

export type DataSourceConfigUpdateDataSourceConfigResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DataSourceConfigDeleteDataSourceConfigData = {
    body: UpdateDataSourceConfigM;
    path?: never;
    query?: never;
    url: '/api/v1/DataSourceConfig/delete';
};

export type DataSourceConfigDeleteDataSourceConfigErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DataSourceConfigDeleteDataSourceConfigError = DataSourceConfigDeleteDataSourceConfigErrors[keyof DataSourceConfigDeleteDataSourceConfigErrors];

export type DataSourceConfigDeleteDataSourceConfigResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DataSourceConfigToggleDataSourceConfigData = {
    body: ToggleDataSourceConfigM;
    path?: never;
    query?: never;
    url: '/api/v1/DataSourceConfig/toggle';
};

export type DataSourceConfigToggleDataSourceConfigErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DataSourceConfigToggleDataSourceConfigError = DataSourceConfigToggleDataSourceConfigErrors[keyof DataSourceConfigToggleDataSourceConfigErrors];

export type DataSourceConfigToggleDataSourceConfigResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TagListTagsData = {
    body: ListTagM;
    path?: never;
    query?: never;
    url: '/api/v1/Tag/list';
};

export type TagListTagsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TagListTagsError = TagListTagsErrors[keyof TagListTagsErrors];

export type TagListTagsResponses = {
    /**
     * Response Tag-Listtags
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type TagListTagsResponse = TagListTagsResponses[keyof TagListTagsResponses];

export type TagMergeTagsData = {
    body: MergeTagM;
    path?: never;
    query?: never;
    url: '/api/v1/Tag/merge';
};

export type TagMergeTagsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TagMergeTagsError = TagMergeTagsErrors[keyof TagMergeTagsErrors];

export type TagMergeTagsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TagRenameTagData = {
    body: RenameTagM;
    path?: never;
    query?: never;
    url: '/api/v1/Tag/rename';
};

export type TagRenameTagErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TagRenameTagError = TagRenameTagErrors[keyof TagRenameTagErrors];

export type TagRenameTagResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TagAddSynonymData = {
    body: AddSynonymM;
    path?: never;
    query?: never;
    url: '/api/v1/Tag/addSynonym';
};

export type TagAddSynonymErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TagAddSynonymError = TagAddSynonymErrors[keyof TagAddSynonymErrors];

export type TagAddSynonymResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TagRemoveSynonymData = {
    body: RemoveSynonymM;
    path?: never;
    query?: never;
    url: '/api/v1/Tag/removeSynonym';
};

export type TagRemoveSynonymErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TagRemoveSynonymError = TagRemoveSynonymErrors[keyof TagRemoveSynonymErrors];

export type TagRemoveSynonymResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type TagTagStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/Tag/stats';
};

export type TagTagStatsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ScheduledTaskListScheduledTasksData = {
    body: ListScheduledTaskM;
    path?: never;
    query?: never;
    url: '/api/v1/ScheduledTask/list';
};

export type ScheduledTaskListScheduledTasksErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScheduledTaskListScheduledTasksError = ScheduledTaskListScheduledTasksErrors[keyof ScheduledTaskListScheduledTasksErrors];

export type ScheduledTaskListScheduledTasksResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ScheduledTaskAddScheduledTaskData = {
    body: AddScheduledTaskM;
    path?: never;
    query?: never;
    url: '/api/v1/ScheduledTask/add';
};

export type ScheduledTaskAddScheduledTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScheduledTaskAddScheduledTaskError = ScheduledTaskAddScheduledTaskErrors[keyof ScheduledTaskAddScheduledTaskErrors];

export type ScheduledTaskAddScheduledTaskResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ScheduledTaskUpdateScheduledTaskData = {
    body: UpdateScheduledTaskM;
    path?: never;
    query?: never;
    url: '/api/v1/ScheduledTask/update';
};

export type ScheduledTaskUpdateScheduledTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScheduledTaskUpdateScheduledTaskError = ScheduledTaskUpdateScheduledTaskErrors[keyof ScheduledTaskUpdateScheduledTaskErrors];

export type ScheduledTaskUpdateScheduledTaskResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ScheduledTaskDeleteScheduledTaskData = {
    body: DeleteScheduledTaskM;
    path?: never;
    query?: never;
    url: '/api/v1/ScheduledTask/delete';
};

export type ScheduledTaskDeleteScheduledTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScheduledTaskDeleteScheduledTaskError = ScheduledTaskDeleteScheduledTaskErrors[keyof ScheduledTaskDeleteScheduledTaskErrors];

export type ScheduledTaskDeleteScheduledTaskResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ScheduledTaskToggleScheduledTaskData = {
    body: ToggleScheduledTaskM;
    path?: never;
    query?: never;
    url: '/api/v1/ScheduledTask/toggle';
};

export type ScheduledTaskToggleScheduledTaskErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScheduledTaskToggleScheduledTaskError = ScheduledTaskToggleScheduledTaskErrors[keyof ScheduledTaskToggleScheduledTaskErrors];

export type ScheduledTaskToggleScheduledTaskResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ScheduledTaskRunNowData = {
    body: RunNowM;
    path?: never;
    query?: never;
    url: '/api/v1/ScheduledTask/runNow';
};

export type ScheduledTaskRunNowErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScheduledTaskRunNowError = ScheduledTaskRunNowErrors[keyof ScheduledTaskRunNowErrors];

export type ScheduledTaskRunNowResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ScheduledTaskPreviewNextData = {
    body: PreviewCronM;
    path?: never;
    query?: never;
    url: '/api/v1/ScheduledTask/previewNext';
};

export type ScheduledTaskPreviewNextErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ScheduledTaskPreviewNextError = ScheduledTaskPreviewNextErrors[keyof ScheduledTaskPreviewNextErrors];

export type ScheduledTaskPreviewNextResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PushGetPreferenceData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/Push/getPreference';
};

export type PushGetPreferenceResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PushUpdatePreferenceData = {
    body: UpdatePreferenceM;
    path?: never;
    query?: never;
    url: '/api/v1/Push/updatePreference';
};

export type PushUpdatePreferenceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PushUpdatePreferenceError = PushUpdatePreferenceErrors[keyof PushUpdatePreferenceErrors];

export type PushUpdatePreferenceResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PushListMessagesData = {
    body: ListMessagesM;
    path?: never;
    query?: never;
    url: '/api/v1/Push/listMessages';
};

export type PushListMessagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PushListMessagesError = PushListMessagesErrors[keyof PushListMessagesErrors];

export type PushListMessagesResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PushMarkAsReadData = {
    body: MarkAsReadM;
    path?: never;
    query?: never;
    url: '/api/v1/Push/markAsRead';
};

export type PushMarkAsReadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PushMarkAsReadError = PushMarkAsReadErrors[keyof PushMarkAsReadErrors];

export type PushMarkAsReadResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PushUnreadCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/Push/unreadCount';
};

export type PushUnreadCountResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PushResendData = {
    body: ResendM;
    path?: never;
    query?: never;
    url: '/api/v1/Push/resend';
};

export type PushResendErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PushResendError = PushResendErrors[keyof PushResendErrors];

export type PushResendResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type PrivateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type PrivateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PrivateCreateUserError = PrivateCreateUserErrors[keyof PrivateCreateUserErrors];

export type PrivateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PrivateCreateUserResponse = PrivateCreateUserResponses[keyof PrivateCreateUserResponses];
